image: python:3.7

before_script:
  - python --version

stages:
  - test

unit-test-job:
  stage: test
  script:
    - echo "Running tests.."

lint-test-job:
  stage: test
  script:
    - echo "Running code style checks.."
